### PR TITLE
Emit an error if row and header size mismatch

### LINKED ISSUE #621: `encodeGivenHeaders` allows different number of headers than the number of columns with actual data
when using `encodeGivenHeaders[A]`, if the number of elements in the `headers` argument is different to the number of columns that are encoded for values of  `A`, it is probably something the user wants to know about and the Stream should probably fail with an error instead of encoding an invalid csv

### PR DESCRIPTION
**Pull request by satabin**
Fixes #621 

A new method is created and the old one is deprecated to keep binary compatibility.

### CODE REVIEW

File: csv/shared/src/main/scala/fs2/data/csv/package.scala [hunk 1]
```diff
@@ -217,6 +221,27 @@ package object csv {
     }
   }
 
+  /** Encode a specified type into a CSV prepending the given headers. */
+  def encodeWithGivenHeaders[T]: PartiallyAppliedEncodeWithGivenHeaders[T] =
```
Comment (ybasket) [inline csv/shared/src/main/scala/fs2/data/csv/package.scala:225]: Wdyt about renaming to ``encodeWithHeaders`? We already have `encodeWithoutHeaders`, so the naming feels a bit more consistent then the `WithGiven`.

No strong opinion on this though, just noticed it, decide as you see fit.

File: csv/shared/src/test/scala/fs2/data/csv/RowGeneratorTest.scala [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+object RowGeneratorTest extends SimpleIOSuite {
+
+  pureTest("Emit error on wrong row size (#621)") {
+    val input = List(
+      Row(NonEmptyList.of("a", "b", "c"), Some(1)),
+      Row(NonEmptyList.of("d", "e"), Some(2)),
+      Row(NonEmptyList.of("f", "g", "h", "i"), Some(3)),
+      Row(NonEmptyList.of("j", "k", "l"), Some(4))
+    )
+    val headers = NonEmptyList.of("first", "second", "third")
```
Comment (ybasket) [inline csv/shared/src/test/scala/fs2/data/csv/RowGeneratorTest.scala:31]:
```suggestion
    val headers = NonEmptyList.of("first", "second", "third")
    val input = List(
      Row(NonEmptyList.of("a", "b", "c"), Some(1)),
      Row(NonEmptyList.of("d", "e"), Some(2)),
      Row(NonEmptyList.of("f", "g", "h", "i"), Some(3)),
      Row(NonEmptyList.of("j", "k", "l"), Some(4))
    )
```

I find this test case slightly annoying to read, but except for this reordering (so it matches output order) and maybe adding some `unapplySeq` in cats itself, I found no better.

**Review by ybasket — APPROVED** [review]

File: csv/shared/src/test/scala/fs2/data/csv/RowGeneratorTest.scala (hunk 2 above)
Comment (ybasket) [reply csv/shared/src/test/scala/fs2/data/csv/RowGeneratorTest.scala:31]: One more thought on this snippet (not to be done in this PR though): Maybe a `row"…, …, …"` string interpolator could be nice, especially for our tests?

File: csv/shared/src/main/scala/fs2/data/csv/package.scala (hunk 1 above)
Comment (satabin) [reply csv/shared/src/main/scala/fs2/data/csv/package.scala:225]: I wanted to keep consistent naming between the high and low level naming. Since the low level naming cannot be `writeWithHeaders`(this is the deprecated one) and high-level cannot be `encodeGivenHeaders` (this is the deprecated one), I settled for merging both.

File: csv/shared/src/test/scala/fs2/data/csv/RowGeneratorTest.scala (hunk 2 above)
Comment (ybasket) [reply csv/shared/src/test/scala/fs2/data/csv/RowGeneratorTest.scala:31]: Tried adding `unapplySeq` to cats, unfortunately it doesn't work because `NonEmptyList` is a `case class` and hence has a generated `unapply` that takes precedence. Would need a dedicated extractor object.
